--------------------------------------------------------
--  File created - Wednesday-September-05-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OUTGOING
--------------------------------------------------------

  CREATE TABLE "WEBAROO"."OUTGOING" 
   (	"MESSAGEID" NUMBER, 
	"PHONENUMBER" VARCHAR2(20 BYTE), 
	"MESSAGETEXT" VARCHAR2(500 BYTE), 
	"SUCCESSSTATUS" VARCHAR2(20 BYTE), 
	"ATTEMPTCOUNT" NUMBER, 
	"SUBMITTEDTIME" NUMBER DEFAULT NULL, 
	"PROCESSEDTIME" NUMBER DEFAULT NULL, 
	"MIPRESPONSEID" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"TRANSACTIONMODE" VARCHAR2(5 BYTE), 
	"DELIVERYTIME" TIMESTAMP (6), 
	"ORDERQUESTID" NUMBER(*,0), 
	"MASK" VARCHAR2(30 BYTE), 
	"PRIORITY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RULES
--------------------------------------------------------

  CREATE TABLE "WEBAROO"."RULES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RULE_PROPERTIES
--------------------------------------------------------

  CREATE TABLE "WEBAROO"."RULE_PROPERTIES" 
   (	"ID" NUMBER, 
	"RULE_ID" NUMBER, 
	"VENDOR_LOAD_BALANCE" VARCHAR2(45 BYTE), 
	"VENDOR_REGEX" VARCHAR2(45 BYTE), 
	"VENDOR_PRIORITY" VARCHAR2(45 BYTE), 
	"VENDOR_FAILOVER_SEQUENCE" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SCHEMAINFO
--------------------------------------------------------

  CREATE TABLE "WEBAROO"."SCHEMAINFO" 
   (	"DATABASE_TYPE" VARCHAR2(20 BYTE), 
	"HOST" VARCHAR2(20 BYTE), 
	"DATABASE" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TABLE_NAME" VARCHAR2(20 BYTE), 
	"QUERY" VARCHAR2(500 BYTE), 
	"COLUMNS" VARCHAR2(100 BYTE), 
	"CONDITION" VARCHAR2(100 BYTE), 
	"STATUS" NUMBER, 
	"PRIORITY" VARCHAR2(20 BYTE), 
	"RULE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VENDORS
--------------------------------------------------------

  CREATE TABLE "WEBAROO"."VENDORS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VENDOR_PARAMS
--------------------------------------------------------

  CREATE TABLE "WEBAROO"."VENDOR_PARAMS" 
   (	"ID" NUMBER, 
	"VENDOR_ID" NUMBER, 
	"PROTOCOL" VARCHAR2(20 BYTE), 
	"URL" VARCHAR2(200 BYTE), 
	"PARAMS" VARCHAR2(300 BYTE), 
	"MULTI_MESSAGE_SUPPORT" NUMBER, 
	"UNICODE_SUPPORT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WEBAROO.OUTGOING
SET DEFINE OFF;
Insert into WEBAROO.OUTGOING (MESSAGEID,PHONENUMBER,MESSAGETEXT,SUCCESSSTATUS,ATTEMPTCOUNT,SUBMITTEDTIME,PROCESSEDTIME,MIPRESPONSEID,TRANSACTIONMODE,DELIVERYTIME,ORDERQUESTID,MASK,PRIORITY) values (1,'919833598918','test1','INPROCESS',1,1346760115,1346760117,'2074070730044768424',null,null,null,null,null);
Insert into WEBAROO.OUTGOING (MESSAGEID,PHONENUMBER,MESSAGETEXT,SUCCESSSTATUS,ATTEMPTCOUNT,SUBMITTEDTIME,PROCESSEDTIME,MIPRESPONSEID,TRANSACTIONMODE,DELIVERYTIME,ORDERQUESTID,MASK,PRIORITY) values (2,'918652323111','helllo again','INPROCESS',1,1346760115,1346760117,'2074070730044768424',null,null,null,null,null);
Insert into WEBAROO.OUTGOING (MESSAGEID,PHONENUMBER,MESSAGETEXT,SUCCESSSTATUS,ATTEMPTCOUNT,SUBMITTEDTIME,PROCESSEDTIME,MIPRESPONSEID,TRANSACTIONMODE,DELIVERYTIME,ORDERQUESTID,MASK,PRIORITY) values (3,'919411471630','testing','INPROCESS',1,1346760115,1346760117,'2074070730044768424',null,null,null,null,null);
REM INSERTING into WEBAROO.RULES
SET DEFINE OFF;
REM INSERTING into WEBAROO.RULE_PROPERTIES
SET DEFINE OFF;
REM INSERTING into WEBAROO.SCHEMAINFO
SET DEFINE OFF;
REM INSERTING into WEBAROO.VENDORS
SET DEFINE OFF;
REM INSERTING into WEBAROO.VENDOR_PARAMS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index RULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAROO"."RULES_PK" ON "WEBAROO"."RULES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RULE_PROPERTIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAROO"."RULE_PROPERTIES_PK" ON "WEBAROO"."RULE_PROPERTIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VENDORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAROO"."VENDORS_PK" ON "WEBAROO"."VENDORS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VENDOR_PARAMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAROO"."VENDOR_PARAMS_PK" ON "WEBAROO"."VENDOR_PARAMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C006987
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAROO"."SYS_C006987" ON "WEBAROO"."OUTGOING" ("MESSAGEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table OUTGOING
--------------------------------------------------------

  ALTER TABLE "WEBAROO"."OUTGOING" ADD PRIMARY KEY ("MESSAGEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RULES
--------------------------------------------------------

  ALTER TABLE "WEBAROO"."RULES" ADD CONSTRAINT "RULES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBAROO"."RULES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."RULES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."RULES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RULE_PROPERTIES
--------------------------------------------------------

  ALTER TABLE "WEBAROO"."RULE_PROPERTIES" ADD CONSTRAINT "RULE_PROPERTIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBAROO"."RULE_PROPERTIES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCHEMAINFO
--------------------------------------------------------

  ALTER TABLE "WEBAROO"."SCHEMAINFO" MODIFY ("PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."SCHEMAINFO" MODIFY ("DATABASE" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."SCHEMAINFO" MODIFY ("HOST" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."SCHEMAINFO" MODIFY ("DATABASE_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENDORS
--------------------------------------------------------

  ALTER TABLE "WEBAROO"."VENDORS" ADD CONSTRAINT "VENDORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBAROO"."VENDORS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."VENDORS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENDOR_PARAMS
--------------------------------------------------------

  ALTER TABLE "WEBAROO"."VENDOR_PARAMS" ADD CONSTRAINT "VENDOR_PARAMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBAROO"."VENDOR_PARAMS" MODIFY ("UNICODE_SUPPORT" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."VENDOR_PARAMS" MODIFY ("MULTI_MESSAGE_SUPPORT" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."VENDOR_PARAMS" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."VENDOR_PARAMS" MODIFY ("PROTOCOL" NOT NULL ENABLE);
  ALTER TABLE "WEBAROO"."VENDOR_PARAMS" MODIFY ("ID" NOT NULL ENABLE);


--------------------------------------------------------
--  Ref Constraints for Table RULE_PROPERTIES
--------------------------------------------------------

  ALTER TABLE "WEBAROO"."RULE_PROPERTIES" ADD CONSTRAINT "FK_RULE_ID" FOREIGN KEY ("RULE_ID")
	  REFERENCES "WEBAROO"."RULES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEMAINFO
--------------------------------------------------------

  ALTER TABLE "WEBAROO"."SCHEMAINFO" ADD CONSTRAINT "FK_SCHEMA_RULE_ID" FOREIGN KEY ("RULE_ID")
	  REFERENCES "WEBAROO"."RULES" ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table VENDOR_PARAMS
--------------------------------------------------------

  ALTER TABLE "WEBAROO"."VENDOR_PARAMS" ADD CONSTRAINT "FK_VENDOR_RULE_ID" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "WEBAROO"."VENDORS" ("ID") ENABLE;
